version: "3"

services:
  processing-service:
    restart: always
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./processing-service:/app
