version: "3"

services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: car_ranker
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  processing-service:
    restart: always
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: car_ranker
      POSTGRES_HOST: db
      DEBUG: 1
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./processing-service:/app
      - assets:/app/assets
    secrets:
      - postgres_password
  web-api:
    restart: always
    build:
      context: ./web-api
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: car_ranker
      POSTGRES_HOST: db
      JWT_KEY_FILE: /run/secrets/jwt_key
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./web-api:/usr/src/app
      - assets:/usr/src/app/assets
    secrets:
      - postgres_password
      - jwt_key

volumes:
  assets:

secrets:
  postgres_password:
    file: ./docker_postgres_password
  jwt_key:
    file: ./docker_jwt_key
