version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: car_ranker
    secrets:
      - postgres_password
  processing-service:
    restart: always
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: car_ranker
      POSTGRES_HOST: db
      DEBUG: 1
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./processing-service:/app
      - assets:/app/assets
    secrets:
      - postgres_password

volumes:
  assets:

secrets:
  postgres_password:
    file: ./docker_postgres_password.txt
