version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: postgres
    secrets:
      - postgres_password
  processing-service:
    restart: always
    build:
      context: ./processing-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./processing-service:/app
      - assets:/app/assets

volumes:
  assets:

secrets:
  postgres_password:
    file: ./docker_postgres_password.txt
