"""make_aliases

Revision ID: 34057c648f8c
Revises: 713d6e7b298c
Create Date: 2021-01-16 23:54:41.546779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34057c648f8c'
down_revision = '713d6e7b298c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('make_aliases')
    # ### end Alembic commands ###
