"""init

Revision ID: 713d6e7b298c
Revises: 
Create Date: 2021-01-16 23:50:34.048323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713d6e7b298c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_score_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('interior_score', sa.Integer(), nullable=False),
    sa.Column('exterior_score', sa.Integer(), nullable=False),
    sa.Column('equipment_score', sa.Integer(), nullable=False),
    sa.Column('design_score', sa.Integer(), nullable=False),
    sa.Column('run_costs_score', sa.Integer(), nullable=False),
    sa.Column('maintenance_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=64), nullable=False),
    sa.Column('type_full', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('horse_power', sa.Integer(), nullable=False),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('first_registration_year', sa.Integer(), nullable=False),
    sa.Column('first_registration_date', sa.Date(), nullable=True),
    sa.Column('transmission_type', sa.Enum('automatic', 'automatic_cvt', 'manual', name='transmissiontype'), nullable=False),
    sa.Column('fuel_type', sa.Enum('gasoline', 'diesel', name='fueltype'), nullable=False),
    sa.Column('body_type', sa.Enum('sedan', 'suv', 'minivan', 'pickup', 'hatchback', 'coupe', 'station_wagon', 'convertible', name='bodytype'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=False),
    sa.Column('drive_type', sa.Enum('awd', 'fwd', 'rwd', name='drivetype'), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('consumption_combined', sa.Float(), nullable=True),
    sa.Column('exterior_front_image_id', sa.Integer(), nullable=True),
    sa.Column('exterior_side_image_id', sa.Integer(), nullable=True),
    sa.Column('exterior_back_image_id', sa.Integer(), nullable=True),
    sa.Column('interior_front_image_id', sa.Integer(), nullable=True),
    sa.Column('interior_dash_image_id', sa.Integer(), nullable=True),
    sa.Column('interior_back_image_id', sa.Integer(), nullable=True),
    sa.Column('interior_trunk_image_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['exterior_back_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['exterior_front_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['exterior_side_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['interior_back_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['interior_dash_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['interior_front_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['interior_trunk_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_score_weight_id', sa.Integer(), nullable=False),
    sa.Column('interior_score', sa.Integer(), nullable=False),
    sa.Column('exterior_score', sa.Integer(), nullable=False),
    sa.Column('equipment_score', sa.Integer(), nullable=False),
    sa.Column('design_score', sa.Integer(), nullable=False),
    sa.Column('run_costs_score', sa.Integer(), nullable=False),
    sa.Column('maintenance_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['car_score_weight_id'], ['car_score_weights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars_images')
    op.drop_table('car_scores')
    op.drop_table('cars')
    op.drop_table('makes')
    op.drop_table('images')
    op.drop_table('car_score_weights')
    # ### end Alembic commands ###
